- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  become: true

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: true
  become: true

- name: Create MySQL database
  mysql_db:
    name: "{{ mysql_database }}"
    state: present
  become: true

- name: Create MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL"
    state: present
  become: true