- name: Install apache httpd  (state=present is optional)
  ansible.builtin.apt:
    name: "{{ apache_package }}"
    state: present
    update_cache: yes

- name: Start apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
  become: yes