- name: Setup Apache, MySQL, and Python Environment
  hosts: all
  become: yes
  roles:
    - apache
    - mysql
    - php
    - wordpress

- name: Install and start Apache2
  hosts: all
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is running
      service:
        name: apache2
        state: started

- name: Install Python packages
  hosts: all
  become: yes
  tasks:
    - name: Ensure python3 and pip are installed
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install PyMySQL using pip
      pip:
        name: PyMySQL

- name: Start and enable MySQL service
  hosts: all
  become: yes
  tasks:
    - name: Ensure MySQL is started and enabled
      service:
        name: mysql
        state: started
        enabled: yes

- name: Set MySQL root password
  hosts: all
  become: yes
  tasks:
    - name: Ensure MySQL root password is set
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        state: present
        host: localhost
      delegate_to: localhost

  handlers:
  - name: Install git
    ansible.builtin.dnf:
      name: httpd
      state: present
      update_cache: yes  