- hosts: all
  vars:
    src: /home/ubuntu/Ansible-homework-batch6/HW5
    dest: ./
  become: yes
  tasks:
  - name: Install and start Apache
    include: apache.yml
  - name: Install php
  - name: Install wordpress
  - name: Install mysql